@startuml c4
!include  https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

LAYOUT_LEFT_RIGHT()

title Диаграмма контейнеров "DevQuest"

System_Ext(jira, "Корпоративный Трекер", "Источник рабочих задач (Jira/GitLab/Planfix)")

Container_Boundary(devquest, "Платформа DevQuest") {
    Container(web_app, "Web Interface", "React", "Личный кабинет: , магазин, арена дуэлей")
    
    Container_Boundary(backend_services, "Backend (FastAPI)") {
        Container(api, "Main API", "FastAPI", "Обработка запросов фронтенда и логика RPG")
        Container(hook_handler, "Integration Service", "FastAPI/Webhooks", "Принимает сигналы от трекера и конвертирует их в опыт")
    }
    
    ContainerDb(db, "Database", "PostgreSQL", "Прогресс, логи дуэлей, баланс")
}

Rel(jira, hook_handler, "События (Task Done/Started)", "Webhook/JSON")
Rel(hook_handler, db, "Начисляет XP/Gold", "SQL")
Rel(web_app, api, "Запросы данных", "HTTPS/JSON")
Rel(api, db, "Чтение/Запись", "SQL")

@enduml