@startuml
!NEW_C4_STYLE=0
' !include  https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include <C4/C4_Context>
SHOW_PERSON_OUTLINE()

title Диаграмма системного контекста КИС "DevQuest" С4L1

Person(employee, "Сотрудник", "Разработчик или инженер. Выполняет задачи, развивает персонажа, участвует в дуэлях, совершает покупки.")
Person(curator, "Куратор (TL/HR)", "Руководитель. Настраивает ценность задач, просматривает аналитику и судит дуэли.")

System(devquest, "DevQuest", "Система геймификации мотивации сотрудников. Рассчитывает опыт и ценность задач, хранит профили сотрудников и управляет магазином.")

System_Ext(tracker, "Планировщик задач API", "Внешняя система управления проектами. Источник данных о рабочих задачах.")
System_Ext(notif, "Система уведомлений", "Корпоративная почта или мессенджер для оповещений о событиях системы.")

Rel(employee, devquest, "Выбирает задачи, качает статы, покупает бонусы", "HTTPS/Web")
Rel(curator, devquest, "Разрабатывает тематические ивенты, выгружает отчеты, разрешает исход дуэлей", "HTTPS/Web")

Rel_D(devquest, tracker, "Синхронизирует статусы задач, получает метрики", "JSON/REST API")
Rel_D(devquest, notif, "Отправляет уведомления о новых задача, ивентах, достижениях", "SMTP/API")

@enduml